### ISSUE TITLE
Failed to load native Mesos library from /opt/mesosphere/lib/libmesos.so

### ISSUE THREAD

**Issue by veacks** [mesosphere/jenkins-mesos#17]
Impossible to load libmesos.so and install jenkins for Mesos on Marathon.

libmesos.so have been built form sources on the Slave and exposed as volume to the jenkins Container to `/opt/mesosphere/lib` as required in the docker file.

Here is my jenkins.json for Marathon

```json
{
  "id": "jenkins",
  "cpus": 1,
  "mem": 1024,
  "instances": 1,
  "env": {
    "CATALINA_OPTS": "-Xms512m -Xmx512m -Dport.http=$PORT0 -Dcontext.path=$JENKINS_CONTEXT",
    "JENKINS_FRAMEWORK_NAME": "jenkins",
    "JENKINS_CONTEXT": "jenkins.service.consul",
    "LD_LIBRARY_PATH": "/opt/mesosphere/lib"
  },
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "mesosphere/jenkins:0.1.2",
      "network": "HOST"
    },
    "volumes": [{
      "containerPath": "/var/jenkins_home",
      "hostPath": "/tmp/jenkins",
      "mode": "RW"
    },{
      "containerPath": "/opt/mesosphere/lib",
      "hostPath": "/opt/mesosphere/src/.libs",
      "mode": "RO"
    }]
  },
  "healthChecks": [{
    "path": "jenkins.service.consul",
    "portIndex": 0,
    "protocol": "HTTP",
    "gracePeriodSeconds": 30,
    "intervalSeconds": 60,
    "timeoutSeconds": 20,
    "maxConsecutiveFailures": 3
  }]
}
```

When I do a `sudo docker -it <jenkinsContainerId> bash` I can find the the mesos lib at `/opt/mesosphere/lib` with all the mesos libs files.

This is what returns stdout:

```log
--container="mesos-b2f0ddd2-3c4d-4275-b629-7750806f05a6-S0.9206b5f0-08c3-4564-814d-4b7b8ad76523" --docker="docker" --docker_socket="/var/run/docker.sock" --help="false" --initialize_driver_logging="true" --logbufsecs="0" --logging_level="INFO" --mapped_directory="/mnt/mesos/sandbox" --quiet="false" --sandbox_directory="/var/mesos/slaves/b2f0ddd2-3c4d-4275-b629-7750806f05a6-S0/frameworks/b2f0ddd2-3c4d-4275-b629-7750806f05a6-0000/executors/jenkins.7000f2d5-b364-11e5-bdf3-02429d09a80d/runs/9206b5f0-08c3-4564-814d-4b7b8ad76523" --stop_timeout="0ns"
--container="mesos-b2f0ddd2-3c4d-4275-b629-7750806f05a6-S0.9206b5f0-08c3-4564-814d-4b7b8ad76523" --docker="docker" --docker_socket="/var/run/docker.sock" --help="false" --initialize_driver_logging="true" --logbufsecs="0" --logging_level="INFO" --mapped_directory="/mnt/mesos/sandbox" --quiet="false" --sandbox_directory="/var/mesos/slaves/b2f0ddd2-3c4d-4275-b629-7750806f05a6-S0/frameworks/b2f0ddd2-3c4d-4275-b629-7750806f05a6-0000/executors/jenkins.7000f2d5-b364-11e5-bdf3-02429d09a80d/runs/9206b5f0-08c3-4564-814d-4b7b8ad76523" --stop_timeout="0ns"
Registered docker executor on master-slave
Starting task jenkins.7000f2d5-b364-11e5-bdf3-02429d09a80d
Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
Killing docker task
Shutting down
```

This is what returns Mesos stderr:

```log
I0105 04:26:06.435848  8001 exec.cpp:134] Version: 0.25.0
I0105 04:26:06.450709  8007 exec.cpp:208] Executor registered on slave b2f0ddd2-3c4d-4275-b629-7750806f05a6-S0
Warning: '-c' is deprecated, it will be replaced by '--cpu-shares' soon. See usage.
WARNING: Your kernel does not support swap limit capabilities, memory limited without swap.
05-Jan-2016 04:26:10.218 WARNING [main] org.apache.catalina.core.StandardContext.setPath A context path must either be an empty string or start with a '/' and do not end with a '/'. The path [jenkins.service.consul] does not meet these criteria and has been changed to [/jenkins.service.consul]
05-Jan-2016 04:26:10.234 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.27
05-Jan-2016 04:26:10.234 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Sep 28 2015 08:17:25 UTC
05-Jan-2016 04:26:10.235 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.27.0
05-Jan-2016 04:26:10.235 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
05-Jan-2016 04:26:10.236 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            3.13.0-71-generic
05-Jan-2016 04:26:10.236 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
05-Jan-2016 04:26:10.237 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
05-Jan-2016 04:26:10.237 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_66-internal-b01
05-Jan-2016 04:26:10.238 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
05-Jan-2016 04:26:10.238 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
05-Jan-2016 04:26:10.239 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
05-Jan-2016 04:26:10.239 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
05-Jan-2016 04:26:10.240 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
05-Jan-2016 04:26:10.240 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms512m
05-Jan-2016 04:26:10.241 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx512m
05-Jan-2016 04:26:10.241 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dport.http=31712
05-Jan-2016 04:26:10.241 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcontext.path=jenkins.service.consul
05-Jan-2016 04:26:10.242 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.endorsed.dirs=/usr/local/tomcat/endorsed
05-Jan-2016 04:26:10.242 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
05-Jan-2016 04:26:10.243 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
05-Jan-2016 04:26:10.243 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
05-Jan-2016 04:26:10.243 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /opt/mesosphere/lib:/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
05-Jan-2016 04:26:10.352 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-31712"]
05-Jan-2016 04:26:10.374 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
05-Jan-2016 04:26:10.377 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
05-Jan-2016 04:26:10.379 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
05-Jan-2016 04:26:10.380 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 1138 ms
05-Jan-2016 04:26:10.406 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
05-Jan-2016 04:26:10.407 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.27
05-Jan-2016 04:26:14.663 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
05-Jan-2016 04:26:15.276 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-31712"]
05-Jan-2016 04:26:15.290 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
05-Jan-2016 04:26:15.294 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 4913 ms
05-Jan-2016 04:26:15.727 INFO [pool-6-thread-2] jenkins.InitReactorRunner$1.onAttained Started initialization
05-Jan-2016 04:26:15.853 INFO [pool-6-thread-1] jenkins.InitReactorRunner$1.onAttained Listed all plugins
05-Jan-2016 04:26:15.958 INFO [Loading plugin greenballs] hudson.plugins.greenballs.PluginImpl.start Green Balls!
05-Jan-2016 04:26:16.201 INFO [pool-6-thread-5] jenkins.InitReactorRunner$1.onAttained Prepared all plugins
05-Jan-2016 04:26:16.433 INFO [pool-6-thread-2] jenkins.InitReactorRunner$1.onAttained Started all plugins
05-Jan-2016 04:26:16.437 INFO [pool-6-thread-2] jenkins.InitReactorRunner$1.onAttained Augmented all extensions
05-Jan-2016 04:26:19.616 INFO [pool-6-thread-4] jenkins.InitReactorRunner$1.onAttained Loaded all jobs
05-Jan-2016 04:26:19.749 INFO [Download metadata thread] hudson.model.AsyncPeriodicWork$1.run Started Download metadata
05-Jan-2016 04:26:19.775 INFO [Download metadata thread] hudson.model.AsyncPeriodicWork$1.run Finished Download metadata. 21 ms
Failed to load native Mesos library from /opt/mesosphere/lib/libmesos.so
05-Jan-2016 04:26:19.798 WARNING [MesosCloud.init] org.jenkinsci.plugins.mesos.MesosCloud.restartMesos Failed to load native Mesos library from '/opt/mesosphere/lib/libmesos.so': /opt/mesosphere/lib/libmesos-0.25.0.so: libsvn_delta-1.so.1: cannot open shared object file: No such file or directory
Failed to load native Mesos library from /opt/mesosphere/lib:/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
05-Jan-2016 04:26:19.918 SEVERE [pool-6-thread-3] jenkins.InitReactorRunner$1.onTaskFailed Failed MesosCloud.init
 java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:176)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$7.runTask(Jenkins.java:905)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:106)
	... 8 more
Caused by: java.lang.UnsatisfiedLinkError: /opt/mesosphere/lib/libmesos-0.25.0.so: libsvn_delta-1.so.1: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1854)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.apache.mesos.MesosNativeLibrary.load(MesosNativeLibrary.java:159)
	at org.apache.mesos.MesosNativeLibrary.load(MesosNativeLibrary.java:184)
	at org.jenkinsci.plugins.mesos.MesosCloud.restartMesos(MesosCloud.java:180)
	at org.jenkinsci.plugins.mesos.MesosCloud.init(MesosCloud.java:108)
	... 13 more

05-Jan-2016 04:26:19.927 SEVERE [Jenkins initialization thread] hudson.util.BootFailure.publish Failed to initialize Jenkins
 hudson.util.HudsonFailedToLoad: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.WebAppMain$3.run(WebAppMain.java:237)
Caused by: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:269)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:44)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:916)
	at jenkins.model.Jenkins.<init>(Jenkins.java:815)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:225)
Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:176)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$7.runTask(Jenkins.java:905)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:106)
	... 8 more
Caused by: java.lang.UnsatisfiedLinkError: /opt/mesosphere/lib/libmesos-0.25.0.so: libsvn_delta-1.so.1: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1854)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.apache.mesos.MesosNativeLibrary.load(MesosNativeLibrary.java:159)
	at org.apache.mesos.MesosNativeLibrary.load(MesosNativeLibrary.java:184)
	at org.jenkinsci.plugins.mesos.MesosCloud.restartMesos(MesosCloud.java:180)
	at org.jenkinsci.plugins.mesos.MesosCloud.init(MesosCloud.java:108)
	... 13 more 
```

I don't use DCOS for installing Jenkins, I have installed mesos by Ansible on Ubuntu and want to keep an Ansible only installation of the mesos cluster and all the components.

Any advice to make it work?
Thanks

**Comment by veacks** [comment]
When I try to do launch libmesos on the slave or on the container like this: `$ ./libmeos.so` I have the error `Segmentation fault (core dumped)`

**Comment by ssk2** [comment]
Hi @veacks - I'm afraid this Docker image was only intended to work as a DCOS package. At the moment running it on non DCOS clusters is unsupported. You may have to roll your own setup using the Mesos plugin at https://github.com/jenkinsci/mesos-plugin.

**Comment by veacks** [comment]
Ok, thanks @ssk2 I will try to find a solution with mesos-plugin.
